/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aakansha
 */
package billingsystem;

public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Billinglbl = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        Timelbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BuyerDetailslbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Nametfd = new javax.swing.JTextField();
        ContactNolbl = new javax.swing.JLabel();
        ContactNotfd = new javax.swing.JTextField();
        Emaillbl = new javax.swing.JLabel();
        Emailtfd = new javax.swing.JTextField();
        Addresslbl = new javax.swing.JLabel();
        Adresstfd = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        ProductIdlbl = new javax.swing.JLabel();
        ProductIdtfd = new javax.swing.JTextField();
        ProductNamelbl = new javax.swing.JLabel();
        ProductNametfd = new javax.swing.JTextField();
        Ratelbl = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        Quantitylbl = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        Descriptionlbl = new javax.swing.JLabel();
        Descriptiontfd = new javax.swing.JTextField();
        ADDbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        CalculationDetailslbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Totallbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Totaltfd = new javax.swing.JTextField();
        PaidAmounttfd = new javax.swing.JTextField();
        ReturnAmounttfd = new javax.swing.JTextField();
        Savebtn = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        Closebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/Billing.ani.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 13, 105, -1));

        Billinglbl.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        Billinglbl.setForeground(new java.awt.Color(255, 255, 255));
        Billinglbl.setText("Billing");
        getContentPane().add(Billinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 13, 227, -1));

        Datelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Datelbl.setText("Date");
        Datelbl.setName(""); // NOI18N
        getContentPane().add(Datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 13, 37, -1));

        Timelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Timelbl.setText("Time");
        Timelbl.setName(""); // NOI18N
        getContentPane().add(Timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 65, 36, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setName(""); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 13, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setName(""); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 65, 90, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1208, 10));

        BuyerDetailslbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        BuyerDetailslbl.setForeground(new java.awt.Color(255, 255, 255));
        BuyerDetailslbl.setText("Buyer Details:");
        getContentPane().add(BuyerDetailslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 137, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 195, 50, -1));

        Nametfd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Nametfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 188, 188, -1));

        ContactNolbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ContactNolbl.setText("Contact No:");
        getContentPane().add(ContactNolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 195, 87, -1));

        ContactNotfd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ContactNotfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNotfdActionPerformed(evt);
            }
        });
        getContentPane().add(ContactNotfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 195, 152, -1));

        Emaillbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Emaillbl.setText("Email");
        getContentPane().add(Emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 195, 39, -1));

        Emailtfd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Emailtfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailtfdActionPerformed(evt);
            }
        });
        getContentPane().add(Emailtfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 195, 183, -1));

        Addresslbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Addresslbl.setText("Address");
        getContentPane().add(Addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 195, 63, -1));

        Adresstfd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Adresstfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresstfdActionPerformed(evt);
            }
        });
        getContentPane().add(Adresstfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 195, 162, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 1208, 10));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Product Details :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 260, 210, -1));

        ProductIdlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProductIdlbl.setText("Product Id");
        getContentPane().add(ProductIdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 81, -1));

        ProductIdtfd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ProductIdtfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIdtfdActionPerformed(evt);
            }
        });
        getContentPane().add(ProductIdtfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 100, -1));

        ProductNamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ProductNamelbl.setText("Product Name");
        getContentPane().add(ProductNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 303, -1, 22));

        ProductNametfd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(ProductNametfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 304, 154, -1));

        Ratelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ratelbl.setText("Rate");
        getContentPane().add(Ratelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 304, 43, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 304, 85, -1));

        Quantitylbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Quantitylbl.setText("Quantity");
        getContentPane().add(Quantitylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 304, 68, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 304, 89, -1));

        Descriptionlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descriptionlbl.setText("Description");
        getContentPane().add(Descriptionlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 304, 79, -1));

        Descriptiontfd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Descriptiontfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptiontfdActionPerformed(evt);
            }
        });
        getContentPane().add(Descriptiontfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 304, 292, -1));

        ADDbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADDbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/Add-icon.p.png"))); // NOI18N
        ADDbtn.setText("ADD");
        getContentPane().add(ADDbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 333, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 1208, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 377, 712, 213));

        CalculationDetailslbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CalculationDetailslbl.setText("Calculation Details:");
        getContentPane().add(CalculationDetailslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 416, 446, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 531, 146, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Paid Amount");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 494, 100, -1));

        Totallbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Totallbl.setText("Total");
        getContentPane().add(Totallbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 458, 57, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Return Amount");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 534, 117, -1));

        Totaltfd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Totaltfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotaltfdActionPerformed(evt);
            }
        });
        getContentPane().add(Totaltfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 448, 151, -1));

        PaidAmounttfd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PaidAmounttfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidAmounttfdActionPerformed(evt);
            }
        });
        getContentPane().add(PaidAmounttfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 491, 151, -1));

        ReturnAmounttfd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(ReturnAmounttfd, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 531, 147, -1));

        Savebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/Save.ani.jpg"))); // NOI18N
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 440, 100, 30));

        Resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Resetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/Reset.ani.jpg"))); // NOI18N
        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 480, 100, -1));

        Closebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/close.ani.jpg"))); // NOI18N
        Closebtn.setText("Close");
        Closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 520, 100, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 24, -1, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 190, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/btnsback.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdresstfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresstfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresstfdActionPerformed

    private void EmailtfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailtfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailtfdActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void DescriptiontfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptiontfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptiontfdActionPerformed

    private void ContactNotfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNotfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNotfdActionPerformed

    private void TotaltfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotaltfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotaltfdActionPerformed

    private void PaidAmounttfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidAmounttfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaidAmounttfdActionPerformed

    private void ClosebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClosebtnActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavebtnActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetbtnActionPerformed

    private void ProductIdtfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIdtfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIdtfdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDbtn;
    private javax.swing.JLabel Addresslbl;
    private javax.swing.JTextField Adresstfd;
    private javax.swing.JLabel Billinglbl;
    private javax.swing.JLabel BuyerDetailslbl;
    private javax.swing.JLabel CalculationDetailslbl;
    private javax.swing.JButton Closebtn;
    private javax.swing.JLabel ContactNolbl;
    private javax.swing.JTextField ContactNotfd;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JLabel Descriptionlbl;
    private javax.swing.JTextField Descriptiontfd;
    private javax.swing.JLabel Emaillbl;
    private javax.swing.JTextField Emailtfd;
    private javax.swing.JTextField Nametfd;
    private javax.swing.JTextField PaidAmounttfd;
    private javax.swing.JLabel ProductIdlbl;
    private javax.swing.JTextField ProductIdtfd;
    private javax.swing.JLabel ProductNamelbl;
    private javax.swing.JTextField ProductNametfd;
    private javax.swing.JLabel Quantitylbl;
    private javax.swing.JLabel Ratelbl;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JTextField ReturnAmounttfd;
    private javax.swing.JButton Savebtn;
    private javax.swing.JTable Table;
    private javax.swing.JLabel Timelbl;
    private javax.swing.JLabel Totallbl;
    private javax.swing.JTextField Totaltfd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
