/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Swapnil
 */
public class home extends javax.swing.JFrame {
           public int z=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        btnNewProduct.setVisible(false);
        btnProductDetails.setVisible(false);
        btnBill.setVisible(false);
        btnLogout.setVisible(false);
        btnClose.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHideShow = new javax.swing.JButton();
        btnNewProduct = new javax.swing.JButton();
        btnProductDetails = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1366, 768));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHideShow.setBackground(new java.awt.Color(0, 0, 0));
        btnHideShow.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnHideShow.setForeground(new java.awt.Color(255, 255, 255));
        btnHideShow.setText(">>>");
        btnHideShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHideShowMouseClicked(evt);
            }
        });
        btnHideShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnHideShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 90));

        btnNewProduct.setBackground(new java.awt.Color(255, 204, 204));
        btnNewProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewProduct.setText("New Product");
        btnNewProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnNewProductComponentShown(evt);
            }
        });
        btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 160, 60));

        btnProductDetails.setBackground(new java.awt.Color(255, 204, 204));
        btnProductDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProductDetails.setText("Product Details");
        btnProductDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnProductDetailsComponentShown(evt);
            }
        });
        btnProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 180, 60));

        btnBill.setBackground(new java.awt.Color(255, 204, 204));
        btnBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBill.setText("Bill");
        btnBill.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnBillComponentShown(evt);
            }
        });
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 160, 60));

        btnLogout.setBackground(new java.awt.Color(255, 204, 204));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnLogoutComponentShown(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 170, 60));

        btnClose.setBackground(new java.awt.Color(255, 204, 204));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 460, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 1630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHideShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHideShowActionPerformed

    private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
        // TODO add your handling code here:
       new newProduct().setVisible(true);
    }//GEN-LAST:event_btnNewProductActionPerformed

    private void btnProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductDetailsActionPerformed
        // TODO add your handling code here:
               //new ProductDetails().setVisible(true);

    }//GEN-LAST:event_btnProductDetailsActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
                       new Billing().setVisible(true);

    }//GEN-LAST:event_btnBillActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do You Want To Logout??","Select",JOptionPane.YES_NO_OPTION);
                if(a==0)
                {
                    setVisible(false);
                    new login().setVisible(true);
                }
                    
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do You Want To Exit","Select",JOptionPane.YES_NO_OPTION);
                if(a==0)
                {
                    System.exit(0);
                }
                          
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnHideShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHideShowMouseClicked
        // TODO add your handling code here:
        if(z==0)
        {
        try{
           Thread.sleep(250);
           btnNewProduct.setVisible(true);
        }
        catch(Exception e){
        }
        }
    }//GEN-LAST:event_btnHideShowMouseClicked

    private void btnNewProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnNewProductComponentShown
        // TODO add your handling code here:
         if(z==0)
        {
        try{
           Thread.sleep(250);
           btnProductDetails.setVisible(true);
        }
        catch(Exception e){
        }
        }
    }//GEN-LAST:event_btnNewProductComponentShown

    private void btnProductDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnProductDetailsComponentShown
        // TODO add your handling code here:
         if(z==0)
        {
        try{
           Thread.sleep(250);
           btnBill.setVisible(true);
        }
        catch(Exception e){
        }
        }
    }//GEN-LAST:event_btnProductDetailsComponentShown

    private void btnBillComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnBillComponentShown
        // TODO add your handling code here:
         if(z==0)
        {
        try{
           Thread.sleep(250);
           btnLogout.setVisible(true);
        }
        catch(Exception e){
        }
        }
    }//GEN-LAST:event_btnBillComponentShown

    private void btnLogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnLogoutComponentShown
        // TODO add your handling code here:
         if(z==0)
        {
        try{
           Thread.sleep(250);
           btnClose.setVisible(true);
        }
        catch(Exception e){
        }
        }
    }//GEN-LAST:event_btnLogoutComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHideShow;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewProduct;
    private javax.swing.JButton btnProductDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
