/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingsystem;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Swapnil
 */
public class newProduct extends javax.swing.JFrame {

    /**
     * Creates new form newProduct
     */
    public newProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        labelPID2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        lblDiscription = new javax.swing.JLabel();
        lblActive = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        rateField = new javax.swing.JTextField();
        activeBox = new javax.swing.JComboBox<>();
        discriptonFeild = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/newProduct.JPG"))); // NOI18N
        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 180));
        setMinimumSize(new java.awt.Dimension(500, 350));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblId.setText("Product Id :");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 88, 30));

        labelPID2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPID2.setForeground(new java.awt.Color(255, 0, 0));
        labelPID2.setText("100");
        getContentPane().add(labelPID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 102, -1));

        jLabel4.setText("Product Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 252, -1, 0));

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProductName.setText("Product Name :");
        getContentPane().add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 34));

        lblRate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRate.setText("Product Rate :");
        getContentPane().add(lblRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, 30));

        lblDiscription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDiscription.setText("DisCription:");
        getContentPane().add(lblDiscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 90, 30));

        lblActive.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblActive.setText("Active :");
        getContentPane().add(lblActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 71, -1));

        nameField.setBackground(new java.awt.Color(204, 255, 204));
        nameField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameField.setForeground(new java.awt.Color(204, 204, 204));
        nameField.setText("Enter Product name");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 230, 30));

        rateField.setBackground(new java.awt.Color(204, 255, 204));
        rateField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rateField.setForeground(new java.awt.Color(204, 204, 204));
        rateField.setText("Enter Product Rate");
        rateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rateFieldFocusLost(evt);
            }
        });
        rateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(rateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 230, 30));

        activeBox.setBackground(new java.awt.Color(204, 255, 204));
        activeBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        activeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO", " " }));
        activeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(activeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 220, -1));

        discriptonFeild.setBackground(new java.awt.Color(204, 255, 204));
        discriptonFeild.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        discriptonFeild.setForeground(new java.awt.Color(204, 204, 204));
        discriptonFeild.setText("Enter Discription");
        discriptonFeild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                discriptonFeildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                discriptonFeildFocusLost(evt);
            }
        });
        discriptonFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discriptonFeildActionPerformed(evt);
            }
        });
        getContentPane().add(discriptonFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 230, 30));

        btnSave.setBackground(new java.awt.Color(255, 255, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        btnReset.setBackground(new java.awt.Color(255, 255, 153));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        btnClose.setBackground(new java.awt.Color(255, 255, 153));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 339, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billingsystem/btnsback.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void discriptonFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discriptonFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discriptonFeildActionPerformed

    private void activeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activeBoxActionPerformed

    private void rateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateFieldActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
       setVisible(false);
       new newProduct().setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String pId=btnSave.getText();
        String pName=nameField.getText();
        String rate=rateField.getText();
        String description=discriptonFeild.getText();
        String activate=(String)activeBox.getSelectedItem();
        try{
          Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bms","root","YES");  
          Statement st=con.createStatement();
          st.executeUpdate("insert into product values('"+pId+"','"+pName+"','"+rate+"','"+description+"','"+activate+"') ");
           JOptionPane.showMessageDialog(null, "Successfully Updated !");
           setVisible(false);
           new newProduct().setVisible(true);
           

        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:      
                    setVisible(false);             
    }//GEN-LAST:event_btnCloseActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:
        if(nameField.getText().equals("Enter Product Name"))
        {
           nameField.setText("");
          nameField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
         if(nameField.getText().equals(""))
        {
          nameField.setText("Enter Product Name");
          nameField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void rateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateFieldFocusGained
        // TODO add your handling code here:
          if(rateField.getText().equals("Enter Product Rate"))
        {
           rateField.setText("");
          rateField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_rateFieldFocusGained

    private void rateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateFieldFocusLost
        // TODO add your handling code here:
         if(rateField.getText().equals(""))
        {
          rateField.setText("Enter Product Rate");
          rateField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rateFieldFocusLost

    private void discriptonFeildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discriptonFeildFocusGained
        // TODO add your handling code here:
        if(discriptonFeild.getText().equals("Enter Discription"))
        {
           discriptonFeild.setText("");
          discriptonFeild.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_discriptonFeildFocusGained

    private void discriptonFeildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discriptonFeildFocusLost
        // TODO add your handling code here:
         if(discriptonFeild.getText().equals(""))
        {
          discriptonFeild.setText("Enter Discription");
          discriptonFeild.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_discriptonFeildFocusLost

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bms","root"," ");  
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select max(pId) from product");
        if(rs.first())
        {
          int id=rs.getInt(1);
          id=id+1;
          String str=String.valueOf(id);
          labelPID2.setText(str);
        }
        else
        {
           labelPID2.setText("1");
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activeBox;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField discriptonFeild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelPID2;
    private javax.swing.JLabel lblActive;
    private javax.swing.JLabel lblDiscription;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblRate;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField rateField;
    // End of variables declaration//GEN-END:variables
}
